# Site settings
title: fickle pickle
email: mattybow@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mattybow.github.io" # the base hostname & protocol for your site
twitter_username: dmthigh
github_username:  mattybow
image: Kitten.jpg

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass

include:
  - .nojekyll

exclude:
  - "bower.json"
  - "node_modules"
  - "package.json"
  - "Gemfile"
  - "Gruntfile"
  - "Rakefile"
  - "CNAME"
