# Site settings
title: mattbow portfolio
email: mattybow@gmail.com
description: drop me line, send me a link, I'd love to hear from you
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mattybow.github.io" # the base hostname & protocol for your site
twitter_username: dmthigh
github_username:  mattybow
image: Kitten.jpg
layout: base
permalink: pretty

# Build settings
markdown: kramdown

include:
  - .nojekyll

exclude:
  - "bower.json"
  - "node_modules"
  - "package.json"
  - "Gemfile"
  - "Gruntfile"
  - "Rakefile"
  - "CNAME"
